version: '3.4'

services:
  books_api:
    image: booksapi:dev
    container_name: "Books_API"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Books_API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\tiago\Desktop\Tech_Programming\dotNet\Library_API_dotnet\Library_Api\Books_API:/app:rw
      - C:\Users\tiago\Desktop\Tech_Programming\dotNet\Library_API_dotnet\Library_Api:/src:rw
      - C:\Users\tiago\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\tiago\.nuget\packages:/.nuget/packages:ro
      - C:\Users\tiago\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\tiago\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\tiago\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\tiago\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/Books_API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
  gateway:
    image: gateway:dev
    container_name: "Gateway"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Gateway"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\tiago\Desktop\Tech_Programming\dotNet\Library_API_dotnet\Library_Api\Gateway:/app:rw
      - C:\Users\tiago\Desktop\Tech_Programming\dotNet\Library_API_dotnet\Library_Api:/src:rw
      - C:\Users\tiago\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\tiago\.nuget\packages:/.nuget/packages:ro
      - C:\Users\tiago\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\tiago\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\tiago\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\tiago\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/Gateway.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true

  library_rest_api:
    image: libraryrestapi:dev
    container_name: "Library_Rest_API"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Library_Rest_API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\tiago\Desktop\Tech_Programming\dotNet\Library_API_dotnet\Library_Api\Library_Rest_API:/app:rw
      - C:\Users\tiago\Desktop\Tech_Programming\dotNet\Library_API_dotnet\Library_Api:/src:rw
      - C:\Users\tiago\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\tiago\.nuget\packages:/.nuget/packages:ro
      - C:\Users\tiago\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\tiago\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\tiago\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\tiago\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/Library_Rest_API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true

  reservation_api:
    image: reservationapi:dev
    container_name: "Reservation_API"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Reservation_API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\tiago\Desktop\Tech_Programming\dotNet\Library_API_dotnet\Library_Api\Reservation_API:/app:rw
      - C:\Users\tiago\Desktop\Tech_Programming\dotNet\Library_API_dotnet\Library_Api:/src:rw
      - C:\Users\tiago\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\tiago\.nuget\packages:/.nuget/packages:ro
      - C:\Users\tiago\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\tiago\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\tiago\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\tiago\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/Reservation_API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true
